/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppForm {}
  interface AppFormAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppForm': Components.AppForm;
    'AppRoot': Components.AppRoot;
  }

  interface StencilIntrinsicElements {
    'app-form': Components.AppFormAttributes;
    'app-root': Components.AppRootAttributes;
  }


  interface HTMLAppFormElement extends Components.AppForm, HTMLStencilElement {}
  var HTMLAppFormElement: {
    prototype: HTMLAppFormElement;
    new (): HTMLAppFormElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLElementTagNameMap {
    'app-form': HTMLAppFormElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-form': HTMLAppFormElement;
    'app-root': HTMLAppRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
